### ISSUE TITLE
Clue spans multiple lines and covers part of the grid

### ISSUE THREAD

**Issue by AnichaJSR** [viresh-ratnakar/exolve#12]
Issue: The clue displayed above the grid gets split and spans multiple lines and ends up covering part of the grid. This does not happen all the time but I'm not sure what triggers it.

![Capture5](https://user-images.githubusercontent.com/25233142/65847128-e67e2080-e35d-11e9-8a7c-707cf4ff5f41.PNG)

Version: Exolve v0.16 August 17 2019, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36

**Comment by viresh-ratnakar** [comment]
Hi Anicha, this issue was fixed recently (I think around v0.23). I see that this is the 1AC grid. Sowmya did update the software yesterday, so this issue should go away.

Unfortunately, the browser is often adamant about using old cached versions of javascript files. I see that you are using Chrome. You can go to chrome://settings/clearBrowserData and clear "Cached images and files" and then reload the puzzle, and that should fix it, hopefully. Please do let me know. Thanks!

**Comment by AnichaJSR** [comment]
Ah, I see. Yes, clearing the cache solves the problem. Thanks!
