### ISSUE TITLE
Not working in Firefox 75.0

### ISSUE THREAD

**Issue by Miskeptik** [viresh-ratnakar/exolve#27]
Last version 0.70 not working in Firefox 75.0 (OS Kubuntu 18.04). I trying to open exolve.html or exolve-m.html or test-russian.html. But there are just empty page and nothing. In Chrome 81.0.4044.129 - all right. Version 0.69 in Firefox 75.0 was working.

**Comment by viresh-ratnakar** [comment]
Thanks for filing the bug report!

I've fixed the problem with v0.71. Now, it should work on Firefox for English crosswords.

For other languages, it will still not work on Firefox (but it should now show a meaningful error message). The reason is that Firefox does not yet support Unicode property escapes in regexps. Luckily, the support has been implemented, and I think it will be included in Firefox's 78.0 release. You can track it here, if you are interested: https://bugzilla.mozilla.org/show_bug.cgi?id=1634135

**Comment by viresh-ratnakar** [comment]
Closing the issue (please reopen if needed)
