### ISSUE TITLE
grid filling works poorly in firefox

### ISSUE THREAD

**Issue by martindemello** [viresh-ratnakar/exolve#3]
issues i noticed:

* the cursor has some sort of offset error (it's way to the left of the square)
* hitting left/right/up/down arrows briefly copies the last entered letter where the cursor is

**Comment by viresh-ratnakar** [comment]
thanks, will look!

**Comment by viresh-ratnakar** [comment]
What's the firefox version and device and what's the exolve version? (If you click on "Report bug" from an exolve-rendered grid it should pre-populate all this I think) 

On my phone, firefox does show an issue different from what you found, but seems otherwise OK. On my linux laptop, firefox seems OK.

**Comment by martindemello** [comment]
Version: exolve v0.13 July 29 2019, User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0

**Comment by viresh-ratnakar** [comment]
Hmm, I downloaded Firefox 68 on my laptop and it works fine in that. Can you please try opening one of my files and see if there is any difference? For example, try https://viresh-ratnakar.github.io/gussalufz-13-unsolved.html

Otherwise I'll swing by in person at some point to take a look.

**Comment by martindemello** [comment]
your link worked fine, must have been an issue with the file!
