### ISSUE TITLE
Puzzles cannot be viewed in Internet Explorer

### ISSUE THREAD

**Issue by Raceous** [viresh-ratnakar/exolve#6]
Attached is a screenshot of how a puzzle looks when opened in IE.
This is IE version 11.885.17134.0 on Windows Version 10.0.17134.885.

**Comment by Raceous** [comment]
![1ACGRIDS_ Baking Bread playfully with Pixie Dust - Internet Explorer 8_12_19 5_35_09 PM](https://user-images.githubusercontent.com/54013910/62907459-25adcf00-bd28-11e9-899b-829e1587e5a5.png)

**Comment by viresh-ratnakar** [comment]
I looked into this a bit (in fits and starts unfortunately, as I do not have access to a Windows/IE set-up regularly).

Anything below IE11 will be really hard to support as the JS code is full of the desirably block-scoped "let/const" keywords instead of "var".

Unfortunately, IE11 does not support backtick-enclosed multiline strings in JS, which is how Exolve lets setters describe the entire grid, clues, ninas, questions, etc.

I tried to replace this with '....\n' + for every line (just to diagnose), but it does not work -- there must be other issues too, I suppose. Will keep trying some more, but am not very optimistic, unfortunately.

**Comment by rhythmhq** [comment]
Can you not use Babel to transpile your script into ECMA5?

**Comment by viresh-ratnakar** [comment]
Re: Can you not use Babel to transpile your script into ECMA5?

I think that might be doable, but I do not think that that complexity needs to be a part of the core software, esp as IE seems to be on its way to obsolescence (I *will* try harder to fix Edge issues -- still waiting for a period of time where I have access to a Windows machine for some time). If you try this and are successful, please let me know though. Thanks!

**Comment by viresh-ratnakar** [comment]
Closing the issue as I'm unlikely to work on this, unfortunately.
